// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/indexservice/index_service.proto

package indexservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_OK          Status = 1
	Status_STATUS_ERROR       Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_ERROR",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_ERROR":       2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_indexservice_index_service_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_indexservice_index_service_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_indexservice_index_service_proto_rawDescGZIP(), []int{0}
}

type GetOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffsetRequest) Reset() {
	*x = GetOffsetRequest{}
	mi := &file_proto_indexservice_index_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffsetRequest) ProtoMessage() {}

func (x *GetOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indexservice_index_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffsetRequest.ProtoReflect.Descriptor instead.
func (*GetOffsetRequest) Descriptor() ([]byte, []int) {
	return file_proto_indexservice_index_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetOffsetRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *GetOffsetRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type GetOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=indexservice.Status" json:"status,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // optional human-readable info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffsetResponse) Reset() {
	*x = GetOffsetResponse{}
	mi := &file_proto_indexservice_index_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffsetResponse) ProtoMessage() {}

func (x *GetOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indexservice_index_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetOffsetResponse) Descriptor() ([]byte, []int) {
	return file_proto_indexservice_index_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetOffsetResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *GetOffsetResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetOffsetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PushLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	StartOffset   int64                  `protobuf:"varint,3,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	EndOffset     int64                  `protobuf:"varint,4,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	LogLines      []string               `protobuf:"bytes,5,rep,name=log_lines,json=logLines,proto3" json:"log_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushLogsRequest) Reset() {
	*x = PushLogsRequest{}
	mi := &file_proto_indexservice_index_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLogsRequest) ProtoMessage() {}

func (x *PushLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indexservice_index_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLogsRequest.ProtoReflect.Descriptor instead.
func (*PushLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_indexservice_index_service_proto_rawDescGZIP(), []int{2}
}

func (x *PushLogsRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *PushLogsRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *PushLogsRequest) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *PushLogsRequest) GetEndOffset() int64 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *PushLogsRequest) GetLogLines() []string {
	if x != nil {
		return x.LogLines
	}
	return nil
}

type PushLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=indexservice.Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // optional human-readable info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushLogsResponse) Reset() {
	*x = PushLogsResponse{}
	mi := &file_proto_indexservice_index_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLogsResponse) ProtoMessage() {}

func (x *PushLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indexservice_index_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLogsResponse.ProtoReflect.Descriptor instead.
func (*PushLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_indexservice_index_service_proto_rawDescGZIP(), []int{3}
}

func (x *PushLogsResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *PushLogsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_indexservice_index_service_proto protoreflect.FileDescriptor

const file_proto_indexservice_index_service_proto_rawDesc = "" +
	"\n" +
	"&proto/indexservice/index_service.proto\x12\findexservice\"N\n" +
	"\x10GetOffsetRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\"s\n" +
	"\x11GetOffsetResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.indexservice.StatusR\x06status\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xac\x01\n" +
	"\x0fPushLogsRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12!\n" +
	"\fstart_offset\x18\x03 \x01(\x03R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x04 \x01(\x03R\tendOffset\x12\x1b\n" +
	"\tlog_lines\x18\x05 \x03(\tR\blogLines\"Z\n" +
	"\x10PushLogsResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.indexservice.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*A\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x022\xa7\x01\n" +
	"\fIndexService\x12L\n" +
	"\tGetOffset\x12\x1e.indexservice.GetOffsetRequest\x1a\x1f.indexservice.GetOffsetResponse\x12I\n" +
	"\bPushLogs\x12\x1d.indexservice.PushLogsRequest\x1a\x1e.indexservice.PushLogsResponseB2Z0distributed-logs/proto/indexservice;indexserviceb\x06proto3"

var (
	file_proto_indexservice_index_service_proto_rawDescOnce sync.Once
	file_proto_indexservice_index_service_proto_rawDescData []byte
)

func file_proto_indexservice_index_service_proto_rawDescGZIP() []byte {
	file_proto_indexservice_index_service_proto_rawDescOnce.Do(func() {
		file_proto_indexservice_index_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_indexservice_index_service_proto_rawDesc), len(file_proto_indexservice_index_service_proto_rawDesc)))
	})
	return file_proto_indexservice_index_service_proto_rawDescData
}

var file_proto_indexservice_index_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_indexservice_index_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_indexservice_index_service_proto_goTypes = []any{
	(Status)(0),               // 0: indexservice.Status
	(*GetOffsetRequest)(nil),  // 1: indexservice.GetOffsetRequest
	(*GetOffsetResponse)(nil), // 2: indexservice.GetOffsetResponse
	(*PushLogsRequest)(nil),   // 3: indexservice.PushLogsRequest
	(*PushLogsResponse)(nil),  // 4: indexservice.PushLogsResponse
}
var file_proto_indexservice_index_service_proto_depIdxs = []int32{
	0, // 0: indexservice.GetOffsetResponse.status:type_name -> indexservice.Status
	0, // 1: indexservice.PushLogsResponse.status:type_name -> indexservice.Status
	1, // 2: indexservice.IndexService.GetOffset:input_type -> indexservice.GetOffsetRequest
	3, // 3: indexservice.IndexService.PushLogs:input_type -> indexservice.PushLogsRequest
	2, // 4: indexservice.IndexService.GetOffset:output_type -> indexservice.GetOffsetResponse
	4, // 5: indexservice.IndexService.PushLogs:output_type -> indexservice.PushLogsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_indexservice_index_service_proto_init() }
func file_proto_indexservice_index_service_proto_init() {
	if File_proto_indexservice_index_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_indexservice_index_service_proto_rawDesc), len(file_proto_indexservice_index_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_indexservice_index_service_proto_goTypes,
		DependencyIndexes: file_proto_indexservice_index_service_proto_depIdxs,
		EnumInfos:         file_proto_indexservice_index_service_proto_enumTypes,
		MessageInfos:      file_proto_indexservice_index_service_proto_msgTypes,
	}.Build()
	File_proto_indexservice_index_service_proto = out.File
	file_proto_indexservice_index_service_proto_goTypes = nil
	file_proto_indexservice_index_service_proto_depIdxs = nil
}
